### ISSUE TITLE
Generating new Config removes all succeeding peers

### ISSUE THREAD

**Issue by samboman** [vchrizz/ER-wizard-WireGuard#10] opened 2022-08-25 09:31 UTC
I added 8 new Peers. I needed to generate new config for the third one in the list (from top) in wizard. The new keys and QR was shown. But when I have clicked Apply and reloaded the wizard I only have 3 peers. 1 and 2 are untouched and number 3 are the newly generated config. Peer 4-8 was removed.

I noticed the same thing happens if I try to add multiple peers without reloading the wizard, only the first newlyu generated peer are added, the following peers are not added at all. Maybe related to this bug.
Adding one peer at the time and reloading the wizard works fine.

![image](https://user-images.githubusercontent.com/1038277/186629299-43aa350a-15e5-4f50-8474-fe695a790b18.png)
Green stays, red deleted on Apply.

Also we can see the buttons for Generate config and Add IP are buggy...

But thanks for a good wizard and overview!

**Comment by vchrizz** [comment] 2022-12-16 21:59
There have been changes in config management and before I used /config/user-data/wireguard/wgsettings.json but in the latest release of Wireguard Wizard this file is stale and should be removed. Could you check if you have latest (1.6) version of the wizard running and check that you do not have the wgsettings.json file? If the file is there, rename it and check if the issue happens again. If you still encounter the issue, feel free to reopen.
Regarding the buggy Add IP Button see (fixed) issue #2 .

**Comment by samboman** [comment] 2022-12-17 10:30
![image](https://user-images.githubusercontent.com/1038277/208237525-2a3c616d-034d-4dd2-856b-c9c7f6fb0529.png)
This is the version.

**Comment by vchrizz** [comment] 2022-12-17 11:18
Did you check for wgsettings.json file?

**Comment by samboman** [comment] 2022-12-19 07:44
Sorry, I did check, and it's not there. I have not updated the wizard from an older version. This is the content of: `/config/user-data/wireguard/`

```
$ ls -hl /config/user-data/wireguard
total 376
-rw-rw-r--    1 root     vyattacf   90.0K Aug 22 12:09 ER-wizard-WireGuard.tar
-rw-rw-r--    1 root     vyattacf  150.9K Aug 22 12:09 e50-v2-v1.0.20220627-v1.0.20210914.deb
-rw-rw-r--    1 root     vyattacf  130.0K Dec 19 06:25 wireguard-wizard.log
```

**Comment by vchrizz** [comment] 2023-01-15 14:10
I need help to track this issue down because I could not reproduce it.
Meanwhile I'll let this issue open, if anyone has the same issue and/or finds the root cause to possibly fix this, we can close this issue afterwards.

**Comment by samboman** [comment] 2023-01-16 17:33
Ah, this was not good. Don't know if its related to the other config issue, but after an update to latest hotfix5 of EdgeOS, I ended up with a blank UI, no config are left:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1038277/212737140-bda10a10-bb4c-47d6-ad99-112aec0417e5.png">

Is there a chance I can get it back?

EDIT: I was able to recreate the wg0 sections by a backup of my config.boot - file.

**Comment by samboman** [comment] 2023-01-16 17:36
> There have been changes in config management and before I used /config/user-data/wireguard/wgsettings.json but in the latest release of Wireguard Wizard this file is stale and should be removed. Could you check if you have latest (1.6) version of the wizard running and check that you do not have the wgsettings.json file?

The file are not there, at least not today.

**Comment by samboman** [comment] 2023-01-16 17:49
The update was done 2023-01-16:

```2023-01-09/09:25:53.164490254 [wizard] EdgeMAX WireGuard Wizard started - Session=19461
2023-01-09/09:25:53.234177022 [wizard] WireGuard wizard found at /config/wizard/feature/WireGuard/wizard-run
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-======================================
ii  wireguard      1.0.20220627-1 mipsel       fast, modern, secure kernel VPN tunnel
2023-01-09/09:25:53.314986904 [wizard] wireguard package already installed! checking for new version on disk ...
2023-01-09/09:25:54.154503190 [wizard] latest available wireguard package is already installed: 1.0.20220627-1 (found in /config/user-data/wireguard/)
2023-01-09/09:25:54.896724660 [wizard] latest available wireguard wizard is already installed: 1.6-20211226 (found in /config/user-data/wireguard/)
2023-01-09/09:25:58.989783996 [wizard] EdgeMAX WireGuard Wizard ended - Session=19461
2023-01-16/18:27:44.776389298 [wizard] EdgeMAX WireGuard Wizard started - Session=25531
2023-01-16/18:27:44.869540221 [wizard] WireGuard wizard found at /config/wizard/feature/WireGuard/wizard-run
dpkg-query: no packages found matching wireguard
2023-01-16/18:27:45.045358209 [wizard] wireguard package not installed! need to install packages.
2023-01-16/18:27:45.054522658 [installer] Starting installation of WireGuard from /config/user-data/wireguard/ ...
2023-01-16/18:27:45.071758353 [installer] check if we are online (if we can reach github.com) ...
2023-01-16/18:27:46.003789241 [installer] online-check succeeded ...
2023-01-16/18:27:46.011938449 [installer] Check system where we are running ...
2023-01-16/18:27:46.085942044 [installer] Detected EdgeRouter e50 system ...
2023-01-16/18:27:46.165789942 [installer] Detected EdgeOS version v2 ...
2023-01-16/18:27:46.181410473 [installer] Checking for e50-v2 deb-file in /config/user-data/wireguard ...
2023-01-16/18:27:46.210367982 [installer] WireGuard deb-file e50-v2 found in /config/user-data/wireguard ...
2023-01-16/18:27:46.223660545 [installer] Installing WireGuard for e50-v2 ...
Selecting previously unselected package wireguard.
(Reading database ... 37091 files and directories currently installed.)
Preparing to unpack e50-v2-v1.0.20220627-v1.0.20210914.deb ...
Adding 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to /opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'
Adding 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def.vyatta by wireguard'
Adding 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def.vyatta by wireguard'
Unpacking wireguard (1.0.20220627-1) ...
Setting up wireguard (1.0.20220627-1) ...
2023-01-16/18:27:57.214103396 [installer] WireGuard Wizard tar-file found in /config/user-data/wireguard - installing WireGuard Wizard...
2023-01-16/18:27:57.279165680 [installer] WireGuard wizard found in /config/wizard/feature/WireGuard/wizard-run
2023-01-16/18:27:57.287461836 [installer] Installing WireGuard wizard ...
2023-01-16/18:27:57.340629319 [installer] WireGuard and Wizard installation done.
2023-01-16/18:27:57.349105641 [wizard] wireguard package installed and configured. all done.
2023-01-16/18:27:58.267131715 [wizard] latest available wireguard wizard is already installed: 1.6-20211226 (found in /config/user-data/wireguard/)
2023-01-16/18:27:59.267990038 [wizard] EdgeMAX WireGuard Wizard ended - Session=25531
2023-01-16/18:43:18.504618746 [wizard] EdgeMAX WireGuard Wizard started - Session=26448
2023-01-16/18:43:18.574580761 [wizard] WireGuard wizard found at /config/wizard/feature/WireGuard/wizard-run
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-======================================
ii  wireguard      1.0.20220627-1 mipsel       fast, modern, secure kernel VPN tunnel
2023-01-16/18:43:18.654946942 [wizard] wireguard package already installed! checking for new version on disk ...
2023-01-16/18:43:19.463652979 [wizard] latest available wireguard package is already installed: 1.0.20220627-1 (found in /config/user-data/wireguard/)
2023-01-16/18:43:20.356435008 [wizard] latest available wireguard wizard is already installed: 1.6-20211226 (found in /config/user-data/wireguard/)
2023-01-16/18:43:21.159007710 [wizard] EdgeMAX WireGuard Wizard ended - Session=26448
```

**Comment by tgies** [comment] 2023-01-21 02:51
I have the same issue where reconfiguring a peer nukes all subsequent peers. I have also seen the issue with losing all configuration for wg0 on update and had to recreate that section from my backups before.

I can reliably reproduce the problem where all the subsequent peers in the list get nuked when reconfiguring a peer, on the latest release. I have no wgsettings.json file.

**Comment by Wibout** [comment] 2023-07-30 11:38
It seems this issue is still not solved. I faced exactly the same problem, loosing all subsequent peers when reconfiguring the first peer.

**Comment by Wibout** [comment] 2023-08-05 09:14
@vchrizz, I really hope you can find some time to have a look at this issue as it is quite annoying.

**Comment by samboman** [comment] 2023-08-07 09:44
I also got my config removed when updating the EdgeOS. Very annoying.

**Comment by vchrizz** [comment] 2023-09-16 00:03
Please check out [v1.7-20230916](https://github.com/vchrizz/ER-wizard-WireGuard/releases/tag/v1.7-20230916).
This issue should now be fixed.

**Closed as completed by vchrizz** 2023-09-16 00:03 UTC
