### ISSUE TITLE
Additional "+ Add IP" buttons are not displayed correctly

### ISSUE THREAD

**Issue by MrMartin92** [vchrizz/ER-wizard-WireGuard#2] opened 2021-12-09 08:57 UTC
Hi,

the "+ Add IP" button is not displayed correctly for additional peers. For the first "default" peer it displays fine. See the attached screenshot. I tested Firefox, Chrome and Edge, they are all the same. They are missing the text inside the HTML tag.

![Screenshot 2021-12-09 093125](https://user-images.githubusercontent.com/4492249/145362336-3b24e8c2-224c-4895-a139-bf501009b354.png)

**Comment by vchrizz** [comment] 2021-12-09 14:17
Hi,
to be honest I noticed this issue too and could not find the cause for it yet.
It seems to be related to how the form of the wizard is used and maybe how elements in it are positioned.
As the functionality (to add allowed IPs by clicking the "+") is still given, I see this rather as a minor issue.
To fix this, debugging of Ubiquiti's javascript is required which creates this additional form elements to find out what causes the buttontext to be missing from the second generation of the fields but not on the first generation..

edit: here is described in detail how those EdgeMax wizards work (needs account/login):
- [So you want to add a feature to the EdgeMax Web UI?](https://community.ui.com/questions/So-you-want-to-add-a-feature-to-the-EdgeMax-Web-UI/cb37b069-defa-4f2a-82af-61ea15798dc7)
- [Example for Wizard Validator](https://community.ui.com/questions/Example-for-Wizard-Validator/dc26ad8e-44c8-4a37-955e-9db5e79eeca5#comment/25d4b38c-3bf0-43ad-a91d-0771e05f9c96)

**Comment by vchrizz** [comment] 2021-12-11 17:45
I could not find the exact issue and am struggling to fix it, so I posted the issue to Ubiquiti forums, in the hope someone can help:
[EdgeMax Feature Wizard - WireGuard - nested addable issue](https://community.ui.com/questions/EdgeMax-Feature-Wizard-nested-addable-issue/9c03eb07-a1da-4057-ba95-b2cce1023f1c)

**Comment by vchrizz** [comment] 2021-12-13 23:47
Seems to be an issue with the wizard-functionality. Now with version 1.4 of the wizard this issue happens also with the "Generate config" button, which is also a nested addable like the "Add IP" button.

**Comment by IndrekHaav** [comment] 2022-05-18 11:14
First of all, thanks for the work on this wizard!

So I spent probably way too much time debugging this. It's as you suspected - the problem is with how Ubiquiti's Javascript creates addables. The edge.min.js file contains the following code (beautified and abridged to only contain the relevant parts):

```js
EDGE.Views.Global.WizardBase = Backbone.View.extend({
    initialize: function() {
        this.addLabel = "Add"
    },
    renderAddables: function($$addable$$, $level$$) {
        var $$template$$ = $$addable$$.children(".addable-template").remove(),
            $$add$$0$$ = $$addable$$.children("button.addable-add"),
            $wizard$$ = this;

        $$add$$0$$.on("click", {}, function($event$$, $trigger$$) {
            var $$add$$ = $(this),
                $$clone$$ = $$template$$.clone(!0);
            $wizard$$.addFunction($$add$$, $trigger$$);
            $$clone$$.find("button.addable-add").length && $$clone$$.find("button.addable-add").button({
                icons: {
                    primary: "ui-icon-plus"
                },
                label: $wizard$$.addLabel
            });
        });
    }
});
```

Basically, it finds add buttons in each addable and assigns click handlers, which later get called automatically as the form is rendered. The click handler creates button widgets for each nested add button, and assigns each an icon and label. The label is defined in the `initialize` function, which appears to never be called, so the buttons end up with an empty label. If you remove the `label: $wizard$$.addLabel` part, then the problem disappears.

(Why it doesn't affect the very first addable, I'm not sure. Possibly it uses the original addable-template and only subsequent instances are clones.)

Anyway, since modifying the OS-provided Javascript is probably a bad idea, I came up with the following, **horrible** hack that can be inserted into your wizard.html:

```html
<script>
  $(function () {
    EDGE.Views.Global.WizardBase.prototype.addLabel = function() {
      switch (arguments.callee.caller.caller.caller.caller.caller.caller.caller.caller.caller.arguments[1].parentElement.dataset.object) {
        case 'qrcodeclientconf': return 'Generate config';
        case 'allowed-ips': return 'Add IP';
        default: return null;
      }
    };
  });
</script>
```

It overrides the wizard's `addLabel` property and turns it into a function that gets called when the button widget gets rendered. It then steps up the call tree until the actual `div.callable` element becomes accessible, checks its `object` data attribute and returns an appropriate value. I just stuck it at the very end of the file and it seemed to do the trick. No guarantee it'll keep working, however, since [`Function.caller`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller) is deprecated and [`arguments.callee`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee) doesn't work in strict mode. A better solution would be to get Ubiquiti to fix their Javascript.

**Comment by vchrizz** [comment] 2022-08-05 14:12
Many thanks for your effort!
This also works for me and despite its a "horrible hack" I think this actually is our only option to fix this.
Only downside I see is that after adding your code to wizard.html it breaks adding peers (until the page is reloaded again) once the "Remove peer" button is used.
I guess Ubiquiti won't fix the wizard functionality as it seems there is not much development any more going on on this platform.
I'll add your code nevertheless.

**Comment by vchrizz** [comment] 2022-08-05 15:52
I'm closing this issue for now, feel free to reopen if you want to add anything here.
Thank you @IndrekHaav !

**Closed as completed by vchrizz** 2022-08-05 15:52 UTC

**Comment by IndrekHaav** [comment] 2022-08-06 06:56
NP, happy to help :)
