### ISSUE TITLE
Setup Script wont stay enabled

### ISSUE THREAD

**Issue by JinxCappa** [vchrizz/ER-wizard-WireGuard#11] opened 2022-12-29 01:57 UTC
I can check the box and hit apply but once I refresh the page the option is unticked. `Upgrade Wizard and WireGuard from [GitHub](https://github.com/vchrizz/ER-wizard-WireGuard/) automatically` remains checked though.

wireguard version: 1.0.20220627-1
wizard version: 1.6-20211226

**Comment by tgies** [comment] 2023-01-15 12:32
I just nailed down the cause of this myself, I think. For me, `/config/scripts/pre-config.d/` directory did not exist and this was causing the setup script to not get installed. Fixed by doing `mkdir /config/scripts/pre-config.d` and then applying the wizard with the Setup Script box checked. The setup script then actually gets installed and the checkbox stays checked.

**Comment by vchrizz** [comment] 2023-01-15 13:33
Oh, you are right. Thank you very much for hunting this issue down, because of my configuration/scripts I had `/config/scripts/pre-config.d/` already created and so was not able to reproduce the issue. I just reseted a router and started over from scratch and could verify that this directory does not exist. I will add a `mkdir -p /config/scripts/pre-config.d/` into the wizard.
Thank you!

**Closed as completed** 2023-01-15 13:50 UTC

**Comment by genehand** [comment] 2023-07-26 14:53
That did the trick for me too, will you be cutting a new release with the fix?  Thx!

**Comment by Wibout** [comment] 2023-08-06 08:24
@vchrizz, When will your fix for this issue be released?
